[project]
name = "idx-portfolio-pipeline"
version = "0.1.0"
description = "ETL pipeline for Indonesian stock portfolio analytics"
authors = [
    {name = "Zakihran13",email = "zakisuzaki13@gmail.com"}
]
requires-python = ">=3.12, <3.16"
dependencies = [
    "numpy (>=1.26.0,<3.0.0)",
    "pandas (>=2.2.0,<3.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "playwright (>=1.54.0,<2.0.0)",
    "sqlalchemy (>=2.0.0,<3.0.0)",
    "streamlit (>=1.37.0,<2.0.0)",
    "yfinance (>=0.2.40,<0.3.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "aiometer (>=1.0.0,<2.0.0)",
    "nest-asyncio (>=1.6.0,<2.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "asyncpg (>=0.31.0,<0.32.0)",
    "sqlparse (>=0.5.5,<0.6.0)",
    "inflection (>=0.5.1,<0.6.0)",
    "pymongo (>=4.17.0,<5.0.0)",
    "motor (>=3.7.1,<4.0.0)",
]


[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.poetry]
package-mode = false
[dependency-groups]
dev = [
    "ipykernel (>=7.3.0,<8.0.0)"
]
